In [5]:
import numpy as np

In [36]:
vet = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0])
vet

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1,  0])

In [75]:
unico_vet = np.unique(vet)
unico_vet

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 777])

In [73]:
type(vet)

numpy.ndarray

In [38]:
vet [5]

np.int64(5)

In [39]:
print(vet[5])

5


In [58]:
vet2 = np.array([0,1,2,3,4,5,6,7,8,9,10])
vet2.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [59]:
vet = np.append(vet,777)
vet

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  19,  18,  17,  16,  15,
        14,  13,  12,  11,  10,   9,   8,   7,   6,   5,   4,   3,   2,
         1,   0, 777, 777, 777])

In [60]:
vet.shape

(44,)

In [61]:
vetor = np.array ([[0,1,2,3,4,5,6,7,8]])
vetor.shape

In [64]:
vetor3x2 = np.array([[1,2],[2,3],[3,4]])
vetor2x3 = np.array([[1,2,3],[3,4,5]])

In [91]:
m = np.arange(0,100,7)
m

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [92]:
idades = np.array([44,45,23,23,28,19,20,19,17,51,29,28,31,32])
mediasIA2 = round(idades.mean(),2)
mediasIA2

np.float64(29.21)

In [93]:
x = np.unique(idades)
x

array([17, 19, 20, 23, 28, 29, 31, 32, 44, 45, 51])

In [94]:
resul = round(mediaIA2.mean(),2)
resul

np.float64(29.21)